### ISSUE TITLE
Shorter prem+ times

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/kube#11]
Day and hour prem+ for 600 and 150 coins

**Comment by Flou21** [comment]
@Ekwav status?

**Comment by Ekwav** [comment]
> @Ekwav status?

Low priority

**Comment by Flou21** [comment]
I set it to low prio

**Comment by Ekwav** [comment]
fixed with https://github.com/Coflnet/kube/commit/9bca090fcb5b0ee1c656c88fbe8739cadd2b4819
